### ISSUE TITLE
Error installing malchive using latest version of pysqlite3

### ISSUE THREAD

**Issue by r0ny123** [MITRECND/malchive#6]
Currently, `malchive` installation depends on `pysqlite3`. But with `pysqlite3` version `0.5`, the malchive fails to install correctly.
Here's the error log:
```
Running setup.py install for pysqlite3 did not run successfully.
  exit code: 1
  
  [18 lines of output]
  running install
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pysqlite3
  copying pysqlite3\dbapi2.py -> build\lib.win-amd64-3.9\pysqlite3
  copying pysqlite3\__init__.py -> build\lib.win-amd64-3.9\pysqlite3
  running build_ext
  Builds a C extension linking against libsqlite3 library
  building 'pysqlite3._sqlite3' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\src
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMODULE_NAME="pysqlite3.dbapi2" -I/usr/include -IC:\hostedtoolcache\windows\Python\3.9.13\x64\include -IC:\hostedtoolcache\windows\Python\3.9.13\x64\include -IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include -IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tcsrc\blob.c /Fobuild\temp.win-amd64-3.9\Release\src\blob.obj
  blob.c
  C:\Users\runneradmin\AppData\Local\Temp\pip-install-shz7uje4\pysqlite3_7b7ef[127](https://github.com/r0ny123/floss-testing/actions/runs/4283444050/jobs/7459027956#step:4:128)58c04e8bb0577a99bfa9bcd7\src\blob.h(4): fatal error C1083: Cannot open include file: 'sqlite3.h': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

pysqlite3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Error: Process completed with exit code 1.
```
_**Note: the above log is from the GitHub workflow I set up to test the installation.**_

So, I propose we use GitHub actions to test the installation of `malchive` for various os platforms to ensure installation works properly,

**Comment by malwarefrank** [comment]
Have you tried with pysqlite3 v0.4.8 or any other older version?  This may be a bug with [pysqlite3](https://github.com/coleifer/pysqlite3) itself.

@jxb5151 thoughts?  Could we just move to built-in sqlite3, or are we using specific features from pysqlite3?

**Comment by r0ny123** [comment]
Yes, the installation works with pysqlite3 v0.4.8.
